# Generated by Django 6.0 on 2025-12-15 15:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hotels", "0002_booking"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="date_end",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="booking",
            name="date_start",
            field=models.DateField(),
        ),
    ]
