# Generated by Django 6.0 on 2025-12-16 09:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hotels", "0003_alter_booking_date_end_alter_booking_date_start"),
        ("hotels", "0003_booking_no_overlap"),
    ]

    operations = []
