# Generated by Django 6.0 on 2025-12-16 09:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hotels", "0004_merge_20251216_1238"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="booking",
            name="booking_no_overlap_per_room",
        ),
    ]
