# Generated by Django 6.0 on 2025-12-16 10:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hotels", "0005_remove_booking_booking_no_overlap_per_room"),
    ]

    operations = []
