# Generated by Django 6.0 on 2025-12-16 10:00

from django.contrib.postgres.operations import BtreeGistExtension
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hotels", "0006_enable_btree_gist"),
    ]

    operations = [
        BtreeGistExtension(),
    ]
