# Generated by Django 6.0 on 2025-12-16 10:03

import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hotels", "0007_enable_btree_gist"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.CheckConstraint(
                condition=models.Q(("date_start__lt", models.F("date_end"))),
                name="booking_start_before_end",
            ),
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(
                expressions=[
                    (models.F("room"), "="),
                    (
                        models.Func(
                            models.F("date_start"),
                            models.F("date_end"),
                            models.Value("[)"),
                            function="daterange",
                            output_field=django.contrib.postgres.fields.ranges.DateRangeField(),
                        ),
                        "&&",
                    ),
                ],
                name="booking_no_overlap_per_room",
            ),
        ),
    ]
